[package]
name = "qirlib"
version = "0.1.0"
edition = "2018"

[dependencies]
llvm-sys = "110"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm11-0"] }

[lib]
name = "qirlib"
