[package]
name = "pyqir"
version = "0.1.0"
edition = "2018"

[dependencies]
qirlib = {path = "qirlib"}

[dependencies.pyo3]
version = "0.13.2"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]

[lib]
name = "pyqir"
crate-type = ["cdylib"]